services:
  safeline-db:
    image: postgres:16
    container_name: safeline-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: safeline
    ports:
      - "5432:5432"
    volumes:
      - safeline_pg_data_2:/var/lib/postgresql/data
    networks:
      - safeline-network

volumes:
  safeline_pg_data_2:

networks:
  safeline-network:
    driver: bridge
